### ISSUE TITLE
Add function for square-root of BigInt

### ISSUE THREAD

**Issue by tanyakr12** [tanyakr12/bigInt#10]
Currently we have no function for doing square root of any BigInt.

**Comment by ghost** [comment]
Hi @tanyakr12, I would like to work on it. Can you assign this to me?

**Comment by tanyakr12** [comment]
Sure @tanya17-05 :)

**Comment by tanyakr12** [comment]
Sorry @tanya17-05 I mistakenly provided the wrong name and description of the issue. Would you still like to work on this?

**Comment by ghost** [comment]
Yeah sure @tanyakr12. No problem :)
