### ISSUE TITLE
`divide_by_2` is not declared

### ISSUE THREAD

**Issue by VinWare** [tanyakr12/bigInt#15]
On compilation, the following error occurs:
```
bigInt.cpp: In function ‘BigInt sqrt(BigInt&)’:
bigInt.cpp:354:5: error: ‘divide_by_2’ was not declared in this scope
  354 |     divide_by_2(right);
      |     ^~~~~~~~~~~```

**Comment by VinWare** [comment]
I would be happy to provide a fix, shortly.

**Comment by tanyakr12** [comment]
Thankyou @VinWare for pointing this out. I wonder how I missed that. Thanks for fixing this. :)

**Comment by VinWare** [comment]
Happy to help @tanyakr12 and thanks for merging!
