### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by tanyakr12** [tanyakr12/bigInt#6]
We need to add contributing.md for newcomers. Can anyone help me for that?
Points to be kept in contributing.md file:
- [ ] Changes shouldnot break application
- [ ] Be respectful to community
- [ ] For any issue contact @tanyakr12

**Comment by ashishpetwal** [comment]
I would like to work on this issue

**Comment by tanyakr12** [comment]
Sure @ashishpetwal

**Comment by ashishpetwal** [comment]
ok I will be back soon!
